apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "<sample>.labels" . | nindent 4 }}
  namespace: {{ .Values.metadata.namespace }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "<sample>.selectorLabels" . | nindent 6 }} 
  strategy:	
   rollingUpdate:	
      maxSurge: {{ .Values.strategy.maxSurge }}
      maxUnavailable:	{{ .Values.strategy.maxUnavailable }}       
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "<sample>.selectorLabels" . | nindent 8 }}
        aadpodidbinding: {{ .Values.AzureIdentity.AzureIdentityBinding.selector }} 
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.volume.enabled }}
      initContainers:
        - name: initcontainer
          image: busybox
          volumeMounts:
          {{- toYaml .Values.volume.configVolumeMounts  | nindent 10 -}}
          {{- toYaml .Values.volume.secretVolumeMounts  | nindent 10 }}
          command: ["/bin/sh"]
          args:
            - -c
            - >-
                cp -rfp /secret/* /config/ &&
                mv /config/* /config/application.properties
      {{- end }}
      containers:        
        - name: {{ .Release.Name }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.envvariables.enabled }}
          env:
          {{- toYaml .Values.envvariables.javaEnv  | nindent 10 -}}
          {{- end }}
          {{- if .Values.volume.enabled }}
          volumeMounts:
          {{- toYaml .Values.volume.configVolumeMounts  | nindent 10 -}}
          {{- end }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
              protocol: {{ .Values.service.protocol }}
          startupProbe:
            {{- toYaml .Values.probes.startupProbe | nindent 12 }}
      {{- if .Values.volume.enabled }}
      volumes:
            {{- toYaml .Values.volume.volumes | nindent 10 }}
      {{- end }}