{{- if .Values.SecretProviderClass.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  namespace: {{ .Values.metadata.namespace }}
  name: {{ .Release.Name }}
  labels:
    {{- include "<sample>.labels" . | nindent 4 }}   
spec:
  provider: azure
  parameters:
    {{- toYaml .Values.SecretProviderClass.parameters  | nindent 4 }} 
    objects:  |
      array:
        - |
          {{- toYaml .Values.SecretProviderClass.secret.objects | nindent 10 }}
{{- end }}

