---
# Source: <sample>/templates/SecretProviderClass.yaml
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  namespace: dev
  name: <sample>
  labels:
    helm.sh/chart: <sample>-0.1.0
    app.kubernetes.io/instance: <sample>
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm   
spec:
  provider: azure
  parameters:
    keyvaultName: <sample>akskeyvault
    tenantId: <sample>
    useVMManagedIdentity: "true"
    userAssignedIdentityID: <sample>
    objects:  |
      array:
        - |
          objectName: <sample>
          objectType: secret
