# Default values for <sample>.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


metadata:
  namespace: dev

replicaCount: 1

image:
  registry:   <sample>acr.azurecr.io
  repository: <sample>
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "dev-0.1.1-<sample>"

strategy:
  maxSurge: 25%
  maxUnavailable: 25%

probes:
  startupProbe:
    httpGet: 
      port: 8080
      path: /
    initialDelaySeconds: 20
    periodSeconds: 10
    failureThreshold: 12


service:
  type: ClusterIP
  port: 8080
  protocol: TCP
  targetPort: 8080


volume:
   enabled: true
   name: secrets-store-inline
   secretVolumeMounts:
   - name: secrets-store-inline
     mountPath: "/secret"
     readOnly: false
   configVolumeMounts:
   - name: config
     mountPath: "/config"
     readOnly: false
   volumes:
     - name: config
       emptyDir:
         medium: Memory
     - name: secrets-store-inline
       csi:
         driver: secrets-store.csi.k8s.io
         readOnly: true
         volumeAttributes:
           secretProviderClass: azure-kvname   


AzureIdentity:
  AzureIdentityBinding:
    selector: azure-pod-identity-binding-selector


SecretProviderClass:
  enabled: true
  name: "{{ .Values.volume.volumes.csi.volumeAttributes.secretProviderClass }}"
  parameters:
    useVMManagedIdentity: "true"          
    keyvaultName: "<sample><sample>"
    userAssignedIdentityID: "<sample>"
    tenantId: "<sample>"  
  secret:
    objects:
      objectName: <sample>dev
      objectType: secret
resources: 
  # # We usually recommend not to specify default resources and to leave this as a conscious
  # # choice for the user. This also increases chances charts run on environments with little
  # # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi


securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

  
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""


envvariables:
  enabled: true
  javaEnv: 
    - name: SECRETS_FILE_PATH 
      value: "config"
    - name: SECRETS_FILE_NAME
      value: "scheduler"      

podAnnotations: {}

podSecurityContext: {}
  # <sample>Group: 2000



ingress:
  enabled: true
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: <sample>
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: <sample>-<sample>.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
  #  - secretName: chart-<sample>-tls
  #    hosts:
  #      - chart-<sample>.local



autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# nodeSelector: {}

tolerations: []

affinity: {}


